name: React CD (Deploy to GitHub Pages)

# Gatilhos: quando o código chega na main ou via botão manual
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# Permissões necessárias para que o robô possa criar a branch gh-pages
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código 📥
        uses: actions/checkout@v4

      - name: Configurar Node.js 🟢
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar e Build 🏗️
        run: |
          npm install
          npm run build

      - name: Deploy para o GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Pasta padrão do Vite
          branch: gh-pages # Branch que o GitHub Pages vai ler
