name: React CD (Deploy to GitHub Pages)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código 📥
        uses: actions/checkout@v4

      - name: Configurar Node.js 🟢
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar e Build 🏗️
        working-directory: ./calculadora # Entra na pasta
        run: |
          npm install
          npm run build

      - name: Deploy para o GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: calculadora/dist # O robô precisa de saber que a dist está dentro da pasta calculadora!
          branch: gh-pages
