name: React CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código 📥
        uses: actions/checkout@v4

      - name: Configurar Node.js 🟢
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar Dependências 📦
        working-directory: ./calculadora # Entra na pasta antes de rodar o npm
        run: npm install

      - name: Executar Testes Unitários 🧪
        working-directory: ./calculadora
        run: npm test

      - name: Validar Build 🏗️
        working-directory: ./calculadora # Entra na pasta
        run: npm run build
